---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCWouZNLQXGDPphpByKhc3a70YmitFYIJxjd+JC4jzUN4aHwVfIXQWM39a+h1bVuF2nw/k8JzhAScPt/T486wcobGfK4bB6VzuwALVM5/ZEUQgCYsq0Ea7Gv5M3CIs+PwyynymlZf4iZ0IbK6xfN6DVf8R/kbqR0sMmKm4Yw6B2oayMPUMV0iBowYrAIyG5maaVCVwPcSF6O0T9GHmOX3hMcINLnO7ByO7Chgj82OcUIIFUljwZeU389WtwWDA8mLaxwPeE6d2H1/kXUC3BT6sbQn9s+/fT5RWkaLCKe/N58C/TT6mHiMnXQPznaLOtEJNRky+aFrB7SZ9+JsjQ+H6h5a/4zSShKjBIZ5reDJmqrdiyMo167p/3lqZuhrAedn+DEtk7YzxTItmvk9C1Nc360W34LHn62rGWnjGYKgyoI5WT405qJcmnuNz9WxPse3sa5mLT4sKDBojRe2QbmvfmkhGlxDMV3llZ2TzYYxImDo+m1I89E2ogTnCyn+u9v15oaPsEv6CDi44PvDFC6yappVC6xg9SNq8DjNijQQtpPW9wFez94dqimFxsGfmbh07auvo3+jYomRyM0VN+gYpCJarrQcwkGGPPr405Wiz7bsCNRL4J4kBFa1ec+EM6nJqMfkCZgkBIsgF5ymKjJeEzO7iySyUFXQQzMx5dZIelsDIVdCJnQeLGu6Oe9vitnXu7FlX/LxJsJO9XHpx/zxWGFcx9gd7/EK2NjH4k/4a4aicTKG3ur9sf6/nzdmEPEVrFdRSSw+xmu4baETC/i805BLbal/ckE8421UA4AF0GXkxoGCPXIKG7UMaYGb0Lb9UerngoSZ+MHdX2/tiikWPEedUElQ==
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: crossplane-system
