apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dynamodb-provider.yaml
  - efs-provider.yaml
  - kms-provider.yaml
  - crossplane-aws-provider.yaml
  - providerconfig.yaml