apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argocd-conf
  namespace: flux-system
spec:
  dependsOn:
   - name: argocd
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/argocd
  prune: true
  wait: true
  timeout: 5m0s