apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ns.yaml
  - helmrepository-argocd.yaml
  - helmrelease-argocd.yaml

patchesStrategicMerge::
- patch/argocd-cm-patch.yaml
- patch/argocd-rbac-cm-patch.yaml