apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: produit2
spec:
  description:  Project for product1
  
  # Source repositories that applications in this project can pull from
  sourceRepos:
  - 'https://github.com/lyc-handson-aws/handson-topic10-product2.git'
  - 'https://github.com/lyc-handson-aws/handson-topic10-services.git'
  - '!https://github.com/lyc-handson-aws/handson-topic10-product1.git'

  #sourceNamespaces:
  # - app2

  # Cluster and namespace destinations that applications in this project can deploy to
  destinations:
  - namespace: app2
    server: https://kubernetes.default.svc

  # Roles and access permissions for this project  
  roles:
  - name: project-admin
    description: Project admin role
    policies:
    - p, proj:produit2:project-admin, applications, *, produit2/*, allow
    - p, proj:produit2:project-admin, repositories, *, produit2/*, allow
    - p, proj:produit2:project-admin, clusters, *, produit2/*, allow
    - p, proj:produit2:project-admin, logs, get, produit2/*, allow
  - name: project-reader
    description: Project read role
    policies:
    - p, proj:produit2:project-reader, applications, get, produit2/*, allow
    - p, proj:produit2:project-reader, applications, sync, produit2/*, allow
    - p, proj:produit2:project-reader, repositories, get, produit2/*, allow
    - p, proj:produit2:project-reader, clusters, get, produit2/*, allow
  - name: project-writer
    description: Project write role
    policies:
    - p, proj:produit2:project-writer, applications, delete, produit2/*, deny
    - p, proj:produit2:project-writer, applications, *, produit2/*, allow
    - p, proj:produit2:project-writer, repositories, update, produit2/*, deny
    - p, proj:produit2:project-writer, repositories, *, produit2/*, allow
    - p, proj:produit2:project-writer, clusters, delete, produit2/*, deny
    - p, proj:produit2:project-writer, clusters, *, produit2/*, allow
  clusterResourceWhitelist:
  - group: 'apiextensions.crossplane.io'
    kind: '*'

